- name: Demo on Global level variables
  hosts: localhost
  vars:
    URL: sample.com
  tasks:
    - name: Print URL variable
      ansible.builtin.debug:
        msg: "{{ URL }}"

- name: Demo on task level variables
  hosts: localhost
  tasks:
    - name: Print URL1 variable
      ansible.builtin.debug:
        msg: {{ "URL1" }}
      vars:
          URL1: sample.com


