- name: lookup ssm parameter store in specified region
  hosts: localhost
  tasks:
    - name: Print values from SSM
      debug: msg="{{ lookup('amazon.aws.aws_ssm', 'sample1', region='us-east-1' ) }}"
